spring.application.name=riskengine

# PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/loan_db
spring.datasource.username=postgres
spring.datasource.password=ojas28

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Optional (better logging)
spring.jpa.properties.hibernate.format_sql=true